### PR TITLE
Authenticated encryption support

### LINKED ISSUE #22: Authenticated encryption
Current implementation of config encryption-decryption (which delegates to `com.evolutiongaming.crypto.Crypto#encryptAES` and `com.evolutiongaming.crypto.Crypto#decryptAES` methods) doesn't guarantee plaintext authenticity - if a wrong private key is used on decryption, you'd get a garbage value in return.

I propose to change the default cipher from AES/CTR to AES/GCM which provides authenticated encryption. In implementation it would mean that after the change if a wrong key is used on decryption, you will get an exception instead of a garbage output.

`AES/GCM/NoPadding` cipher with 128 bit key is required to be supported on all JDKs 11+:
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/crypto/Cipher.html

I will provide an implementation PR shortly. I intend to do it in a backward compatible way by using the existing versioning infrastructure.

### PR DESCRIPTION
**Pull request by migesok**
resolves #22 

- refactored Crypto, removed unused and obsolete parts, fixed scaladocs
- added version 3 of encryption with authenticated encryption based on AES/GCM
- Crypto.decryptAES and DecryptConfig now throw exceptions if a wrong private key is used on decryption
- prepared changes for 1.6 release and updated README accordingly
- updated Scala versions

### CODE REVIEW

**Comment by mr-git** [comment]
might be good to update README with `1.6` as version in dependency sample

**Comment by mr-git** [comment]
seems that coverage plugin(s) have to be updated too - 2.13.1 builds failed

**Comment by t3hnar** [comment]
@migesok  could you please fix the builds ?

**Comment by migesok** [comment]
I will look into Travis tomorrow

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 1]
```diff
@@ -1,149 +1,202 @@
...
+
+    def encrypt(value: String, privateKey: String): String = {
+      val skeySpec = aesSKey128bitWithSha256(privateKey.getBytes(UTF_8))
+      val iv = new Array[Byte](IVLengthBytes)
+      secureRandom.nextBytes(iv)
+      val parameterSpec = new GCMParameterSpec(AuthTagLengthBits, iv)
+      val cipher = Cipher.getInstance(CipherTransformation)
+      cipher.init(Cipher.ENCRYPT_MODE, skeySpec, parameterSpec)
+      val encryptedValue = cipher.doFinal(value.getBytes(UTF_8))
+      Base64.encodeBase64String(iv ++ encryptedValue)
```
Comment (arthepsy) [inline src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: I would suggest including IV size in base64-encoded output, for it to be more resilient and future-proof, as IV can be from 8 till 2^(64-1) bits (multiples of 8). Hard-coding IV size now, in future, will force to create new object (like, AES_V4) when different IV size will be needed.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 2]
```diff
@@ -1,149 +1,202 @@
...
+    }
+
+    def decrypt(value: String, privateKey: String): String = {
+      val ivWithEncryptedData = Base64.decodeBase64(value)
+      val skeySpec = aesSKey128bitWithSha256(privateKey.getBytes(UTF_8))
+      val cipher = Cipher.getInstance(CipherTransformation)
+      if (ivWithEncryptedData.length < IVLengthBytes) {
+        throw new IllegalArgumentException("invalid data size")
+      }
+      val (iv, encryptedData) = ivWithEncryptedData.splitAt(IVLengthBytes)
```
Comment (arthepsy) [inline src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: If IV is implemented to be dynamic (as previously suggested), make sure it's not less than 96 bits; otherwise, reject.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 1 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Would 1 byte be enough to encode IV size? I means we effectively limiting it to 255 max.

**Comment by migesok** [comment]
@mr-git README version fixed

**Comment by migesok** [comment]
The build should be fixed now but I need some time to address the comments

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 3]
```diff
@@ -1,149 +1,202 @@
...
-    cipher.init(Cipher.ENCRYPT_MODE, skeySpec)
-    val encryptedValue = cipher.doFinal(value.getBytes("utf-8"))
-    // return a formatted, versioned encrypted string
-    // '2-*' represents an encrypted payload with an IV
-    // '1-*' represents an encrypted payload without an IV
-    Option(cipher.getIV) match {
-      case Some(iv) => s"2-${Base64.getEncoder.encodeToString(iv ++ encryptedValue)}"
-      case None => s"1-${Base64.getEncoder.encodeToString(encryptedValue)}" // will never fall here as CTR requires IV
-    }
+    s"3-${ AES_V3.encrypt(value, privateKey) }"
```
[the remark this answers is not in the document]
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: I don't think the structure of the resulting string should be explained and documented to the lib clients.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 1 above)
Comment (arthepsy) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Yes. I do not expect that larger IV would be beneficial as it still gets hashed into 128 bits and then one has to take into account hash collision probability for security.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 2 above)
Comment (arthepsy) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Also, make sure to add some sanity check for the whole ciphertext length depending on IV size, e.g., if IV size is specified larger than ciphertext itself.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 1 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Done, please check.
I made it in a way that 12 bytes min check is not needed as the size is encoded as an unsigned byte with 0 meaning 12 bytes size - this give max IV size of 255 + 12 bytes

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 2 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: It's already covered, please check

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 4]
```diff
@@ -1,149 +1,202 @@
...
   }
 
+
```
[the remark this answers is not in the document]
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: removed, please check

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 5]
```diff
@@ -1,149 +1,226 @@
...
+      val encryptedValue = cipher.doFinal(value.getBytes(UTF_8))
+      encodeEncryptedToString(iv, encryptedValue)
+    }
+
+    private def encodeEncryptedToString(iv: Array[Byte], encryptedValue: Array[Byte]): String = {
+      //1 byte for dynamic IV length encoding
+      val buf = ByteBuffer.allocate(1 + iv.length + encryptedValue.length)
+      require(iv.length >= MinIVLengthBytes, s"IV length shouldn't be smaller than $MinIVLengthBytes bytes")
+      //encode IV length as an unsigned byte starting from MinIVLengthBytes
+      buf.put((iv.length - MinIVLengthBytes).toByte)
```
Comment (arixmkii) [inline src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Doesn't look like a good idea to me. At some point you might want to bump the minimal threshold and it will break all the data encrypted before. What is the benefit of adding this complexity instead of just validating input of this method? It makes this code less portable. My opinion that encoded value should contain all the data needed for decryption and not rely on any magic numbers.

Comment (arixmkii) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Even having 12 of all available options useless still leaves a lot of room in range 0-255, what should be totally enough for foreseeable future.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 6]
```diff
@@ -1,149 +1,226 @@
...
+      val decryptInputLength = payload.size - ivEndIdx
+      val decryptedValue = try {
+        cipher.doFinal(payload, ivEndIdx, decryptInputLength)
+      } catch {
+        case e: AEADBadTagException => throw new DecryptAuthException(e)
+      }
+      new String(decryptedValue, UTF_8)
+    }
+
+    private def readValidIvLength(payload: Array[Byte]): Int = {
```
Comment (arixmkii) [inline src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: This will be not needed if the length is stored inside encrypted value as is. A bit less magic.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (arixmkii) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Yes, this is internal format. Just use data generated by any version crypto < current version and you should be fine. It is not an open format or any standard.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 1 above)
Comment (arthepsy) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: I agree with @arixmkii, there's no need for "0 meaning 12", just use 0-255 and reject 0-11. It will still be fine. And it is more transparent.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 5 above)
Comment (arthepsy) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: There won't be a need to bump threshold, but other than that, I agree with @arixmkii. No need for such complexity. Usable range 12-255 will still be fine.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 1 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Agree. I've changed length encoding as you suggested, please check

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 5 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Agree. I've changed length encoding as you suggested, please check

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 6 above)
Comment (arixmkii) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Ok to keep it as additional sanity check.

File: src/test/scala/com/evolutiongaming/crypto/CryptoSpec.scala [hunk 7]
```diff
@@ -107,5 +105,63 @@ class CryptoSpec extends AnyFlatSpec with Matchers {
...
+    val key = "1234567890123456"
+    val original = "secretvalue"
+
+    val encrypted = encryptV3WithIVLength(key, original, 11)
+
+    intercept[IllegalArgumentException] {
+      Crypto.decryptAES(encrypted, key)
+    }
+  }
   // enb of backward compatibility tests
```
Comment (arthepsy) [inline src/test/scala/com/evolutiongaming/crypto/CryptoSpec.scala]: typo

Comment (migesok) [reply src/test/scala/com/evolutiongaming/crypto/CryptoSpec.scala]: Good catch, thanks! Fixed

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 8]
```diff
@@ -1,149 +1,225 @@
...
-  private def validateAesKeyLength(key: String): Unit =
-    require(key.getBytes("utf-8").length <= AesKeyBytesMaxSize, throw new AesKeyTooLong)
+  /** AES legacy V0 (no versioning) mode support - it has restrictions on key size */
+  private object AES_V0 {
+    private val CipherAlgorithm = "AES"
+    private val CipherTransformation = "AES"
+
+    def decrypt(value: String, privateKey: String): String = {
+      val privateKeyBytes = privateKey.getBytes(UTF_8)
+      require(privateKeyBytes.length <= AesKeyBytesMaxSize, throw new AesKeyTooLong)
```
Comment (t3hnar) [inline src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: why not just put `if` instead of `require` ?

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 9]
```diff
@@ -1,149 +1,225 @@
...
+      val effectiveSecretKey = privateKeyBytes.take(AesKeyBytesMaxSize)
+      val skeySpec = new SecretKeySpec(effectiveSecretKey, CipherAlgorithm)
+      val cipher = Cipher.getInstance(CipherTransformation)
+      cipher.init(Cipher.DECRYPT_MODE, skeySpec)
+      new String(cipher.doFinal(Hex.decodeHex(value)))
```
Comment (t3hnar) [inline src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: could we have method call per line? so in case of exceptions it is visible which failed ?

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 10]
```diff
@@ -1,149 +1,225 @@
...
+import org.apache.commons.codec.binary.{Base64, Hex}
+import org.apache.commons.codec.digest.DigestUtils
 
 /**
   * Copyright (C) 2009-2016 Lightbend Inc. <https://www.lightbend.com>
   *
   * Based on https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/libs/Crypto.scala
   */
 object Crypto {
-  val aesTransformation: String = "AES/CTR/NoPadding"
```
[the remark this answers is not in the document]
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Yes, thanks for pointing this out! It breaks compilation compatibility. I will bump the version

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 11]
```diff
@@ -1,149 +1,225 @@
...
-    *
-    * @param value      An hexadecimal encrypted string.
-    * @param privateKey The key used to encrypt.
-    * @return The decrypted String.
+    * @param value      an encrypted string produced by the [[encryptAES]] method
+    * @param privateKey private key string used in encryption
+    * @return decrypted string
     */
   def decryptAES(value: String, privateKey: String): String = {
-    val seperator = "-"
```
[the remark this answers is not in the document]
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Finally fixed!

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 8 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: yep, I didn't notice it. Looks like an abuse of `require`

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 9 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Agreed.

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 10 above)
[the remark this answers is not in the document]
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Version bumped to 2.0-SNAPSHOT in the build and 2.0.0 in the README

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala [hunk 12]
```diff
@@ -1,149 +1,225 @@
...
+  class DecryptAuthException(cause: Throwable) extends Exception(
+    "Decrypted value is not the original one, most likely wrong private key used for decryption",
+    cause,
+  )
+
+  /*
+  using lazy val to postpone init until the first usage so class loading does not get blocked
+  by obtaining entropy for the seed - same trick as in java.util.UUID.Holder
+   */
+  private lazy val secureRandom = new SecureRandom
```
[the remark this answers is not in the document]
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Agreed to leave it as it is

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 8 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Fixed

File: src/main/scala/com/evolutiongaming/crypto/Crypto.scala (hunk 9 above)
Comment (migesok) [reply src/main/scala/com/evolutiongaming/crypto/Crypto.scala]: Fixed all the similar places I found
