### PR TITLE
Provide fallback to plain password for DecryptConfig

### LINKED ISSUE #25: Return lenient default behaviour for DecryptConfig
Before the changes done in https://github.com/evolution-gaming/crypto/pull/23 `DecryptConfig` default behaviour was lenient towards exceptions - it swallowed any failure and returned the given password value as it is.

After the PR the default behaviour changed to a strict one - if the `encryptedPasswords` flag is set, a password must be decrypted correctly or an exception is going to be thrown.
Turns out there are apps in our codebase which depend on the lenient behaviour and it's hard to fix it in all the places.

The proposal is to return the lenient behaviour by default with possibility to have the strict one as well. Probably the method pointing to the lenient behaviour can be marked as deprecated.

### PR DESCRIPTION
**Pull request by Phill101**
With 2.* series we lost so desired fallback mechanism for passwords being treated as un-encrypted on decryption failure.
This PR brings it back with respect of a new `DecryptAuthException`.

Resolves #25

### CODE REVIEW

File: src/main/scala/com/evolutiongaming/crypto/DecryptConfig.scala [hunk 1]
```diff
@@ -16,6 +19,9 @@ object DecryptConfig {
     } else {
       password
     }
+  } catch {
+    case th: DecryptAuthException => throw th
+    case NonFatal(_) => password
```
Comment (t3hnar) [inline src/main/scala/com/evolutiongaming/crypto/DecryptConfig.scala:24]: hm… can we be more specific here?

**Review by t3hnar — CHANGES_REQUESTED** [review]

File: src/main/scala/com/evolutiongaming/crypto/DecryptConfig.scala (hunk 1 above)
Comment (Phill101) [reply src/main/scala/com/evolutiongaming/crypto/DecryptConfig.scala:24]: What do you mean?

Comment (t3hnar) [reply src/main/scala/com/evolutiongaming/crypto/DecryptConfig.scala:24]: I mean that we'd like to fallback to password only in case of some specific errors and not all `NonFatal`, unless I'm missing something

Comment (Phill101) [reply src/main/scala/com/evolutiongaming/crypto/DecryptConfig.scala:24]: I want to return the same behaviour that we have in 1.5.1. I'm afraid there can be various kinds of exceptions thrown (now or in a future) and the common and most natural denominator is `NonFatal` 🤔

**Review by t3hnar — APPROVED** [review]

**Review by arixmkii — APPROVED** [review]
